import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import client from '../sanity'
import { urlFor } from '../sanity'
import { useEffect,useState } from 'react'
import Link from 'next/link'
import Header from '../components/Header'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  // console.log("Hello world");

  const [posts, getPosts] = useState([]);
  useEffect(()=>{
    const query = `*[_type == "post"]| order(_createdAt desc){
      _id,
      title,
      author -> {
        name,
        image
      },
        description,
        slug,
        mainImage
    }`
    client.fetch(query).then(data=>{
      getPosts(data);
    })
  },[]);
  console.log(posts);
  return (
    <>
      
      <Head>
        <title>Mailer-Daemon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {/* <Navbar /> */}
      {posts?.map(post =>{
        return(
        <Link key={post._id} href="/post/${post.slug.current}">
          <div className="image">
            <img className="main image" style={{ height:200 , width:200, marginTop: 50 , marginLeft:50 ,flexDirection : 'row', display: 'inline-block'}} src={urlFor(post.mainImage).url()} alt="" />
            <div className="">
              <div>
                <p className="post title" style={{ fontSize:18,marginLeft:50}}>{post.title}</p>
                <p className="author name" style={{ fontSize:14,marginLeft:50 }} >{/*{post.description}*/} by {post.author.name}</p>
              </div>
              {/* <img className="author image" style={{ height: 80 , width:80, marginLeft:50 }} src={urlFor(post.author.image).url()} alt="" /> */}
            </div>
          </div>
         
        </Link>
        
        
        )
      }
       
        
        
      )}
    </>
  )
}
